parameters:
    database_driver: pdo_pgsql
    database_host: 146.255.102.79
    database_port: null
    database_name: armatucanasta
    database_user: gicsdr
    database_password: gicsdr==$$
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: caef98d3fccbb24bfe1ea45ecea0a4f9891374cf
