homepage:
    pattern:  /hello
    defaults: { _controller: GicsdrArmatucanastaBundle:Default:index }
logout:
    pattern:  /logout
GicsdrArmatucanastaBundle_unidad:
    resource: "@GicsdrArmatucanastaBundle/Resources/config/routing/unidad.yml"
    prefix:   /unidad
GicsdrArmatucanastaBundle_cocina:
    resource: "@GicsdrArmatucanastaBundle/Resources/config/routing/cocina.yml"
    prefix:   /cocina
GicsdrArmatucanastaBundle_conversion:
    resource: "@GicsdrArmatucanastaBundle/Resources/config/routing/conversion.yml"
    prefix:   /conversion
GicsdrArmatucanastaBundle_plato:
    resource: "@GicsdrArmatucanastaBundle/Resources/config/routing/plato.yml"
    prefix:   /plato
GicsdrArmatucanastaBundle_ingrediente:
    resource: "@GicsdrArmatucanastaBundle/Resources/config/routing/ingrediente.yml"
    prefix:   /ingrediente
GicsdrArmatucanastaBundle_insumo:
    resource: "@GicsdrArmatucanastaBundle/Resources/config/routing/insumo.yml"
    prefix:   /insumo
