parameters:
#    gicsdr_armatucanasta.example.class: Gicsdr\ArmatucanastaBundle\Example

services:
#    gicsdr_armatucanasta.example:
#        class: %gicsdr_armatucanasta.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
