insumo:
    pattern:  /
    defaults: { _controller: "GicsdrArmatucanastaBundle:Insumo:index" }

insumo_show:
    pattern:  /{id}/show
    defaults: { _controller: "GicsdrArmatucanastaBundle:Insumo:show" }

insumo_new:
    pattern:  /new
    defaults: { _controller: "GicsdrArmatucanastaBundle:Insumo:new" }

insumo_create:
    pattern:  /create
    defaults: { _controller: "GicsdrArmatucanastaBundle:Insumo:create" }
    requirements: { _method: post }

insumo_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "GicsdrArmatucanastaBundle:Insumo:edit" }

insumo_update:
    pattern:  /{id}/update
    defaults: { _controller: "GicsdrArmatucanastaBundle:Insumo:update" }
    requirements: { _method: post }

insumo_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "GicsdrArmatucanastaBundle:Insumo:delete" }
    requirements: { _method: post }
